# LocalHost 
###
GET http://localhost:8080/contacts
### contact 1
GET http://localhost:8080/contacts/65a9819a8921f52dee618915
### contact 2
GET http://localhost:8080/contacts/65a981c78921f52dee618916
### contact 3
GET http://localhost:8080/contacts/65a981d98921f52dee618918

### create/POST contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Charlie",
  "lastName": "Brown",
  "email": "charlieB@gmail.com",
  "favoriteColor": "purple",
  "birthday": "07/11/95"
}
  
###PUT contact
PUT http://localhost:8080/contacts/65a9819a8921f52dee618915 HTTP/1.1
content-type: application/json

{
    "firstName": "Carrie",
    "lastName": "Jones",
    "email": "carrieJ@gmail.com",
    "favoriteColor": "red",
    "birthday": "05/31/01"
}

###delete contact  
DELETE http://localhost:8080/contacts/65b4273f8dfac3a36fea00d3 HTTP/1.1


#Render
### render all contacts
Get https://week1cse-341.onrender.com/contacts

###POST
POST https://week1cse-341.onrender.com/contacts HTTP/1.1 
 content-type: application/json

{
  "firstName": "Charlie",
  "lastName": "Brown",
  "email": "charlieB@gmail.com",
  "favoriteColor": "purple",
  "birthday": "07/11/95"
}

###PUT 
PUT https://week1cse-341.onrender.com/contacts/65a9819a8921f52dee618915 HTTP/1.1 
content-type: application/json

{
    "firstName": "Carrie",
    "lastName": "Jones",
    "email": "carrieJ@gmail.com",
    "favoriteColor": "red",
    "birthday": "05/31/01"
}

###DELETE
DELETE https://week1cse-341.onrender.com/contacts/65b57b2055b73c1b83530a69 HTTP/1.1 

### render contact 1
Get https://week1cse-341.onrender.com/contacts/65a9819a8921f52dee618915
### render contact 2
Get https://week1cse-341.onrender.com/contacts/65a981c78921f52dee618916
### render contact 3
Get https://week1cse-341.onrender.com/contacts/65a981d98921f52dee618918
